
// ...............................................................................................................................
//
// (C) Copyright  2011/2017 TekGenesis.  All Rights Reserved
// THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF TekGenesis.
// The copyright notice above does not evidence any actual or intended
// publication of such source code.
//
// ...............................................................................................................................

package tekgenesis.metadata.form.widget;

/**
 * Icon Types.
 */
public enum IconType {

    //~ Enum constants ...............................................................................................................................

    NONE, ADJUST, ANCHOR, ARCHIVE, AREA_CHART, ASTERISK, AT, AUTOMOBILE, BAN, BANK, BARCODE, BARS, BEER, BELL, BELL_O, BELL_SLASH, BELL_SLASH_O,
    BICYCLE, BINOCULARS, BIRTHDAY_CAKE, BOLT, BOMB, BOOK, BOOKMARK, BOOKMARK_O, BRIEFCASE, BUG, BUILDING, BUILDING_O, BULLHORN, BULLSEYE, BUS, CAB,
    CALCULATOR, CALENDAR, CALENDAR_O, CAMERA, CAMERA_RETRO, CAR, CC, CERTIFICATE, CHECK, CHECK_CIRCLE, CHECK_CIRCLE_O, CHILD, CIRCLE_THIN, CLOCK_O,
    CLOSE, CLOUD, CLOUD_DOWNLOAD, CLOUD_UPLOAD, CODE, CODE_FORK, COFFEE, COGS, COMMENT, COMMENT_O, COMMENTS, COMMENTS_O, COMPASS, COPYRIGHT, CROP,
    CROSSHAIRS, CUBE, CUBES, CUTLERY, DASHBOARD, DATABASE, DESKTOP, DOWNLOAD, EDIT, ELLIPSIS_H, ELLIPSIS_V, ENVELOPE, ENVELOPE_O, ENVELOPE_SQUARE,
    EXCHANGE, EXCLAMATION, EXCLAMATION_CIRCLE, EXCLAMATION_TRIANGLE, EXTERNAL_LINK, EXTERNAL_LINK_SQUARE, EYE, EYE_SLASH, EYEDROPPER, FAX, FEMALE,
    FIGHTER_JET, FILM, FILTER, FIRE, FIRE_EXTINGUISHER, FLAG, FLAG_CHECKERED, FLAG_O, FLASH, FLASK, FOLDER, FOLDER_O, FOLDER_OPEN, FOLDER_OPEN_O,
    FROWN_O, FUTBOL_O, GAMEPAD, GAVEL, GEARS, GIFT, GLASS, GLOBE, GRADUATION_CAP, GROUP, HDD_O, HEADPHONES, HEART, HEART_O, HISTORY, HOME, IMAGE,
    INBOX, INFO, INSTITUTION, KEY, KEYBOARD_O, LANGUAGE, LAPTOP, LEAF, LEGAL, LEMON_O, LEVEL_DOWN, LEVEL_UP, LIFE_BOUY, LIFE_BUOY, LIFE_RING,
    LIFE_SAVER, LIGHTBULB_O, LOCATION_ARROW, LOCK, MAGIC, MAGNET, MAIL_FORWARD, MAIL_REPLY, MAIL_REPLY_ALL, MALE, MAP_MARKER, MEH_O, MICROPHONE,
    MICROPHONE_SLASH, MINUS, MINUS_CIRCLE, MOBILE, MOBILE_PHONE, MOON_O, MORTAR_BOARD, MUSIC, NAVICON, NEWSPAPER_O, PAINT_BRUSH, PAPER_PLANE,
    PAPER_PLANE_O, PAW, PENCIL, PENCIL_SQUARE, PENCIL_SQUARE_O, PHONE, PHONE_SQUARE, PHOTO, PICTURE_O, PLANE, PLUG, PLUS, PLUS_CIRCLE, POWER_OFF,
    PRINT, PUZZLE_PIECE, QRCODE, QUESTION, QUESTION_CIRCLE, QUOTE_LEFT, QUOTE_RIGHT, RANDOM, RECYCLE, REMOVE, REORDER, REPLY, REPLY_ALL, RETWEET,
    ROAD, ROCKET, RSS, RSS_SQUARE, SEARCH, SEARCH_MINUS, SEARCH_PLUS, SEND, SEND_O, SHARE, SHARE_SQUARE, SHARE_SQUARE_O, SHIELD, SHOPPING_CART,
    SIGN_IN, SIGN_OUT, SIGNAL, SITEMAP, SLIDERS, SMILE_O, SOCCER_BALL_O, SORT, SORT_ALPHA_ASC, SORT_ALPHA_DESC, SORT_AMOUNT_ASC, SORT_AMOUNT_DESC,
    SORT_ASC, SORT_DESC, SORT_DOWN, SORT_NUMERIC_ASC, SORT_NUMERIC_DESC, SORT_UP, SPACE_SHUTTLE, SPOON, STAR, STAR_HALF, STAR_HALF_EMPTY,
    STAR_HALF_FULL, STAR_HALF_O, STAR_O, SUITCASE, SUN_O, SUPPORT, TABLET, TACHOMETER, TAG, TAGS, TASKS, TAXI, TERMINAL, THUMB_TACK, THUMBS_DOWN,
    THUMBS_O_DOWN, THUMBS_O_UP, THUMBS_UP, TICKET, TIMES, TIMES_CIRCLE, TIMES_CIRCLE_O, TINT, TOGGLE_OFF, TOGGLE_ON, TRASH, TRASH_O, TREE, TROPHY,
    TRUCK, TTY, UMBRELLA, UNIVERSITY, UNLOCK, UNLOCK_ALT, UNSORTED, UPLOAD, USER, USERS, VIDEO_CAMERA, VOLUME_DOWN, VOLUME_OFF, VOLUME_UP, WIFI,
    WRENCH, FILE_ARCHIVE_O, FILE_AUDIO_O, FILE_CODE_O, FILE_EXCEL_O, FILE_IMAGE_O, FILE_MOVIE_O, FILE_PDF_O, FILE_PHOTO_O, FILE_PICTURE_O,
    FILE_POWERPOINT_O, FILE_SOUND_O, FILE_VIDEO_O, FILE_WORD_O, FILE_ZIP_O, INFO_CIRCLE, FA_LG, FA_LI, CIRCLE_O_NOTCH, COG, GEAR, REFRESH, SPINNER,
    CHECK_SQUARE, CHECK_SQUARE_O, CIRCLE, CIRCLE_O, DOT_CIRCLE_O, MINUS_SQUARE, MINUS_SQUARE_O, PLUS_SQUARE_O, SQUARE, SQUARE_O, CREDIT_CARD,
    BAR_CHART, BAR_CHART_O, LINE_CHART, PIE_CHART, CNY, DOLLAR, EUR, EURO, GBP, ILS, INR, JPY, KRW, MONEY, RMB, ROUBLE, RUB, RUBLE, RUPEE, SHEKEL,
    SHEQEL, TRY, TURKISH_LIRA, USD, WON, YEN, ALIGN_CENTER, ALIGN_JUSTIFY, ALIGN_LEFT, ALIGN_RIGHT, BOLD, CHAIN, CHAIN_BROKEN, CLIPBOARD, COLUMNS,
    COPY, CUT, DEDENT, ERASER, FILE, FILE_O, FILE_TEXT, FILE_TEXT_O, FILES_O, FLOPPY_O, FONT, HEADER, INDENT, ITALIC, LINK, LIST, LIST_ALT, LIST_OL,
    LIST_UL, OUTDENT, PAPERCLIP, PARAGRAPH, PASTE, REPEAT, ROTATE_LEFT, ROTATE_RIGHT, SAVE, SCISSORS, STRIKETHROUGH, SUBSCRIPT, SUPERSCRIPT, TABLE,
    TEXT_HEIGHT, TEXT_WIDTH, TH, TH_LARGE, TH_LIST, UNDERLINE, UNDO, UNLINK, ANGLE_DOUBLE_DOWN, ANGLE_DOUBLE_LEFT, ANGLE_DOUBLE_RIGHT,
    ANGLE_DOUBLE_UP, ANGLE_DOWN, ANGLE_LEFT, ANGLE_RIGHT, ANGLE_UP, ARROW_CIRCLE_DOWN, ARROW_CIRCLE_LEFT, ARROW_CIRCLE_O_DOWN, ARROW_CIRCLE_O_LEFT,
    ARROW_CIRCLE_O_RIGHT, ARROW_CIRCLE_O_UP, ARROW_CIRCLE_RIGHT, ARROW_CIRCLE_UP, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, ARROWS, ARROWS_H,
    ARROWS_V, CARET_DOWN, CARET_LEFT, CARET_RIGHT, CARET_SQUARE_O_DOWN, CARET_SQUARE_O_LEFT, CARET_SQUARE_O_RIGHT, CARET_SQUARE_O_UP, CARET_UP,
    CHEVRON_CIRCLE_DOWN, CHEVRON_CIRCLE_LEFT, CHEVRON_CIRCLE_RIGHT, CHEVRON_CIRCLE_UP, CHEVRON_DOWN, CHEVRON_LEFT, CHEVRON_RIGHT, CHEVRON_UP,
    HAND_O_DOWN, HAND_O_LEFT, HAND_O_RIGHT, HAND_O_UP, LONG_ARROW_DOWN, LONG_ARROW_LEFT, LONG_ARROW_RIGHT, LONG_ARROW_UP, TOGGLE_DOWN, TOGGLE_LEFT,
    TOGGLE_RIGHT, TOGGLE_UP, ARROWS_ALT, BACKWARD, COMPRESS, EJECT, EXPAND, FAST_BACKWARD, FAST_FORWARD, FORWARD, PAUSE, PLAY, PLAY_CIRCLE,
    PLAY_CIRCLE_O, STEP_BACKWARD, STEP_FORWARD, STOP, WARNING, ADN, ANDROID, ANGELLIST, APPLE, BEHANCE, BEHANCE_SQUARE, BITBUCKET, BITBUCKET_SQUARE,
    BITCOIN, BTC, CC_AMEX, CC_DISCOVER, CC_MASTERCARD, CC_PAYPAL, CC_STRIPE, CC_VISA, CODEPEN, CSS3, DELICIOUS, DEVIANTART, DIGG, DRIBBBLE, DROPBOX,
    DRUPAL, EMPIRE, FACEBOOK, FACEBOOK_SQUARE, FLICKR, FOURSQUARE, GE, GIT, GIT_SQUARE, GITHUB, GITHUB_ALT, GITHUB_SQUARE, GITTIP, GOOGLE,
    GOOGLE_PLUS, GOOGLE_PLUS_SQUARE, GOOGLE_WALLET, HACKER_NEWS, HTML5, INSTAGRAM, IOXHOST, JOOMLA, JSFIDDLE, LASTFM, LASTFM_SQUARE, LINKEDIN,
    LINKEDIN_SQUARE, LINUX, MAXCDN, MEANPATH, OPENID, PAGELINES, PAYPAL, PIED_PIPER, PIED_PIPER_ALT, PINTEREST, PINTEREST_SQUARE, QQ, RA, REBEL,
    REDDIT, REDDIT_SQUARE, RENREN, SHARE_ALT, SHARE_ALT_SQUARE, SKYPE, SLACK, SLIDESHARE, SOUNDCLOUD, SPOTIFY, STACK_EXCHANGE, STACK_OVERFLOW, STEAM,
    STEAM_SQUARE, STUMBLEUPON, STUMBLEUPON_CIRCLE, TENCENT_WEIBO, TRELLO, TUMBLR, TUMBLR_SQUARE, TWITCH, TWITTER, TWITTER_SQUARE, VIMEO_SQUARE, VINE,
    VK, WECHAT, WEIBO, WEIXIN, WINDOWS, WORDPRESS, XING, XING_SQUARE, YAHOO, YELP, YOUTUBE, YOUTUBE_PLAY, YOUTUBE_SQUARE, AMBULANCE, H_SQUARE,
    HOSPITAL_O, MEDKIT, PLUS_SQUARE, STETHOSCOPE, USER_MD, WHEELCHAIR;

    //~ Methods ......................................................................................................................................

    /** Returns icon class name. */
    @SuppressWarnings("NonJREEmulationClassesInClientCode")
    public String getClassName() {
        if (this == NONE) return "";
        return name().toLowerCase().replaceAll("_", "-");
    }
}
